name: cloud_deploy
channels:
 - conda-forge
 - defaults
dependencies:
  - python=3.9.17
  - pip
  - pip:
      - pandas==1.5.3
      - ppscore==1.3.0
      - streamlit==1.35.0
      - extra-streamlit-components==0.1.60
      - unidecode==1.3.7
      - shapely==2.0.2
      - keplergl==0.3.2
      - plotly==5.17.0
      - statsmodels==0.13.2
      - umap-learn==0.5.4
      - lightgbm==3.3.5
      - langchain==0.0.348
      - openai==0.28.1
      - pygwalker==0.4.7
      - explainerdashboard==0.4.7
      - matplotlib==3.6.2
      - fastcluster==1.2.6
      - polars==0.19.12
      - pydantic==1.10.8
      - tiktoken==0.5.1
      - numba==0.55.2
      - docarray==0.39.1
      - redis==5.0.1
      - func-timeout==4.3.5
      - python-dotenv==1.0.0
      - streamlit-feedback==0.1.2
      - pymongo==3.11.0
      - python-jose[all]
      - PyJWT==2.8.0
      - passlib==1.7.4
      - pymongo[srv]
      - si_prefix==1.2.2
      - pybloqs==1.2.13
      - folium==0.15.1
      - seaborn==0.13.1
      - stqdm==0.0.5
      - faiss-cpu==1.8.0
      - streamlit-tree-select==0.0.5
      - streamlit_code_editor==0.1.12
      - pyspark==3.5.1